// Format registry for the MCP server — mirrors the Lua BACKENDS table in
// livefigures.lua (ids, block classes, dark_ok/scene_ok) and the SKILL.md
// format table (use, docs). exts[0] is the canonical file extension.
export const FORMATS = [
  { id: 'excalidraw', exts: ['excalidraw'], block: 'excalidraw', renderer: 'renderer.mjs',
    dark: true, scene: true,
    use: 'Hand-drawn sketch, annotated mockup (Excalidraw scene JSON)', docs: 'https://docs.excalidraw.com/' },
  { id: 'vega-lite', exts: ['vl.json'], block: 'vega-lite', renderer: 'renderer-vega.mjs',
    dark: true, scene: true,
    use: 'Statistical chart (bar/line/scatter/…)', docs: 'https://vega.github.io/vega-lite/docs/' },
  { id: 'vega', exts: ['vg.json'], block: 'vega', renderer: 'renderer-vega.mjs',
    dark: true, scene: true,
    use: 'Force-directed network, custom visualization', docs: 'https://vega.github.io/vega/docs/' },
  { id: 'nomnoml', exts: ['noml', 'nomnoml'], block: 'nomnoml', renderer: 'renderer-text.mjs',
    use: 'Quick boxes-and-arrows, UML-ish', docs: 'https://nomnoml.com/' },
  { id: 'wavedrom', exts: ['wavedrom', 'wavedrom.json'], block: 'wavedrom', renderer: 'renderer-text.mjs',
    use: 'Digital timing / register bit-fields', docs: 'https://wavedrom.com/tutorial.html' },
  { id: 'bytefield', exts: ['bytefield'], block: 'bytefield', renderer: 'renderer-text.mjs',
    use: 'Byte/packet layout (RFC-style)', docs: 'https://bytefield-svg.deepsymmetry.org/' },
  { id: 'graphviz', exts: ['dot', 'gv'], block: 'dot', renderer: 'renderer-graphviz.mjs',
    use: 'Dependency graph, state machine, tree', docs: 'https://graphviz.org/documentation/' },
  { id: 'dbml', exts: ['dbml'], block: 'dbml', renderer: 'renderer-dbml.mjs',
    use: 'Database schema / ER diagram', docs: 'https://dbml.dbdiagram.io/docs/' },
  // kroki-backed (ADR 0012): rendered via a kroki endpoint, network required
  { id: 'plantuml', exts: ['puml', 'plantuml'], block: 'plantuml', renderer: 'renderer-kroki.mjs', krokiType: 'plantuml',
    use: 'UML sequence/class/activity/state', docs: 'https://plantuml.com/' },
  { id: 'd2', exts: ['d2'], block: 'd2', renderer: 'renderer-kroki.mjs', krokiType: 'd2',
    use: 'Modern declarative diagram', docs: 'https://d2lang.com/tour/intro' },
  { id: 'c4', exts: ['c4'], block: 'c4', renderer: 'renderer-kroki.mjs', krokiType: 'c4plantuml',
    use: 'C4 architecture (C4-PlantUML)', docs: 'https://github.com/plantuml-stdlib/C4-PlantUML' },
  { id: 'structurizr', exts: ['structurizr'], block: 'structurizr', renderer: 'renderer-kroki.mjs', krokiType: 'structurizr',
    use: 'C4 architecture (Structurizr DSL)', docs: 'https://docs.structurizr.com/dsl' },
  { id: 'erd', exts: ['erd'], block: 'erd', renderer: 'renderer-kroki.mjs', krokiType: 'erd',
    use: 'ER diagram (terse notation)', docs: 'https://github.com/BurntSushi/erd' },
  { id: 'ditaa', exts: ['ditaa'], block: 'ditaa', renderer: 'renderer-kroki.mjs', krokiType: 'ditaa',
    use: 'ASCII art → diagram', docs: 'https://ditaa.sourceforge.net/' },
  { id: 'pikchr', exts: ['pikchr'], block: 'pikchr', renderer: 'renderer-kroki.mjs', krokiType: 'pikchr',
    use: 'PIC-style technical drawing', docs: 'https://pikchr.org/home/doc/trunk/doc/userman.md' },
  { id: 'svgbob', exts: ['svgbob'], block: 'svgbob', renderer: 'renderer-kroki.mjs', krokiType: 'svgbob',
    use: 'ASCII art → diagram (svgbob)', docs: 'https://ivanceras.github.io/svgbob-editor/' },
  { id: 'tikz', exts: ['tikz'], block: 'tikz', renderer: 'renderer-kroki.mjs', krokiType: 'tikz',
    use: 'LaTeX/TikZ graphics (source must be a complete \\documentclass{standalone} document)', docs: 'https://tikz.dev/' },
];
