project:
  type: website

website:
  title: "livefigures gallery"
  sidebar:
    contents:
      - index.qmd
      - excalidraw.qmd
      - vega.qmd
      - nomnoml.qmd
      - wavedrom.qmd
      - bytefield.qmd
      - plantuml.qmd

format:
  html:
    lightbox: true

filters:
  - at: pre-ast
    path: livefigures
